-- Generated by wallust, do not edit.
-- Consumed by the Lua Hyprland config via require("colors.custom.wallust").
-- bg1 is darker than bg0; bg2..bg4 are derived lighter shades for borders/surfaces.
colors = {
    bg0    = "rgb(050505)",
    bg1    = "rgb(040404)",
    bg2    = "rgb(191919)",
    bg3    = "rgb(282828)",
    bg4    = "rgb(373737)",

    fg     = "rgb(F0F0F0)",

    red    = "rgb(B0B0B0)",
    orange = "rgb(B8B8B8)",
    yellow = "rgb(B8B8B8)",
    green  = "rgb(8E8E8E)",
    aqua   = "rgb(999999)",
    blue   = "rgb(626262)",
    purple = "rgb(707070)",
    pink   = "rgb(707070)",

    grey0  = "rgb(2A2A2A)",
    grey1  = "rgb(2A2A2A)",
    grey2  = "rgb(E0E0E0)",
}
