-- Generated by wallust, do not edit.
-- Consumed by the Lua Hyprland config via require("colors.custom.wallust").
-- bg1 is darker than bg0; bg2..bg4 are derived lighter shades for borders/surfaces.
colors = {
    bg0    = "rgb({{ background | strip }})",
    bg1    = "rgb({{ background | darken(0.3) | strip }})",
    bg2    = "rgb({{ background | lighten(0.08) | strip }})",
    bg3    = "rgb({{ background | lighten(0.14) | strip }})",
    bg4    = "rgb({{ background | lighten(0.20) | strip }})",

    fg     = "rgb({{ foreground | strip }})",

    red    = "rgb({{ color1 | strip }})",
    orange = "rgb({{ color3 | strip }})",
    yellow = "rgb({{ color3 | strip }})",
    green  = "rgb({{ color2 | strip }})",
    aqua   = "rgb({{ color6 | strip }})",
    blue   = "rgb({{ color4 | strip }})",
    purple = "rgb({{ color5 | strip }})",
    pink   = "rgb({{ color5 | strip }})",

    grey0  = "rgb({{ color8 | strip }})",
    grey1  = "rgb({{ color8 | strip }})",
    grey2  = "rgb({{ color7 | strip }})",
}
